### ISSUE TITLE
Scrollbar is not styled

### ISSUE THREAD

**Issue by liz-dominguez** [PredixDev/px-dark-theme#6]
Hi,

I'm using your dark theme in Chrome, and noticed that the scrollbar is not styled like it is inside some components. Is there a way to fix this?

This is a screenshot from the website:
![predix-scrollbar 2](https://user-images.githubusercontent.com/46033283/50307456-56658f00-044d-11e9-8ca9-389020cb174a.JPG)

Thank you :)

**Comment by evanjd** [comment]
Fixing the styling on predix-ui is simple enough, but having `px-dark-theme` style ALL scrollbars in ALL elements is trickier.

Not all browsers support styling the scrollbar, and those that do have all implemented it differently. Furthermore, scroll bar styles are not inherited from parent elements, so you'd have to know which elements you'd want to style (or use a wildcard selector, which would hurt performance).

If you did want to experiment with this on your app, here's some browser-specific CSS you can try:

**Chrome and Safari:**
```css
.your-element-class-here::-webkit-scrollbar {
  background: var(--px-catalog-page-background-color);
}

.your-element-class-here::-webkit-scrollbar-thumb {
  background: var(--px-catalog-page-accent-color--primary);
}
```

**Firefox (64 or later):**
```css
.your-element-class-here {
  scrollbar-color: var(--px-catalog-page-accent-color--primary) var(--px-catalog-page-background-color)
}
```
